export type UnidadeEleitoral = {
    id: number | null;
    sigla: string;
    nome: string;
    regiao: string | null;
    cargos: any | null;
    diretorios: any | null;
    codigo: string;
    capital: boolean;
    estado: string;
};

export type Cargo = {
    codigo: number;
    sigla: string | null;
    nome: string;
    codSuperior: number;
    titular: boolean;
    contagem: number;
};

export type Partido = {
    numero: number;
    sigla: string;
    nome: string | null;
    sqPrestadorConta: number | null;
};

export type Eleicao = {
    id: number;
    siglaUF: string | null;
    localidadeSgUe: string | null;
    ano: number;
    codigo: string | null;
    nomeEleicao: string | null;
    tipoEleicao: string | null;
    turno: string | null;
    tipoAbrangencia: string | null;
    dataEleicao: string | null;
    codSituacaoEleicao: number | null;
    descricaoSituacaoEleicao: string | null;
    descricaoEleicao: string;
};

export type Candidato = {
    id: number;
    nomeUrna: string;
    numero: number;
    idCandidatoSuperior: number | null;
    nomeCompleto: string;
    descricaoSexo: string | null;
    dataDeNascimento: string | null;
    tituloEleitor: string;
    cpf: string | null;
    descricaoEstadoCivil: string | null;
    descricaoCorRaca: string | null;
    descricaoSituacao: string;
    nacionalidade: string | null;
    grauInstrucao: string | null;
    ocupacao: string | null;
    gastoCampanha1T: number | null;
    gastoCampanha2T: number | null;
    sgUfNascimento: string | null;
    nomeMunicipioNascimento: string | null;
    localCandidatura: string | null;
    ufCandidatura: string;
    ufSuperiorCandidatura: string | null;
    codigoSituacaoCandidatoSuperior: number | null;
    dataUltimaAtualizacao: string | null;
    fotoUrl: string | null;
    fotoUrlPublicavel: boolean;
    fotoDataUltimaAtualizacao: string | null;
    descricaoTotalizacao: string;
    nomeColigacao: string;
    composicaoColigacao: string | null;
    descricaoTipoDrap: string | null;
    numeroProcessoDrap: string | null;
    numeroProcessoDrapEncrypt: string | null;
    numeroProcesso: string | null;
    numeroProcessoEncrypt: string | null;
    numeroProcessoPrestContas: string | null;
    numeroProcessoPrestContasEncrypt: string | null;
    numeroProtocolo: string | null;
    cargo: Cargo;
    bens: any | null;
    totalDeBens: number | null;
    vices: any | null;
    partido: Partido;
    eleicao: Eleicao;
    emails: any | null;
    sites: any | null;
    arquivos: any | null;
    eleicoesAnteriores: any | null;
    substituto: any | null;
    motivos: any | null;
    motivoSituacao: string | null;
    codigoSituacaoCandidato: number | null;
    descricaoSituacaoCandidato: string | null;
    isCandidatoInapto: boolean | null;
    codigoSituacaoPartido: number | null;
    descricaoSituacaoPartido: string | null;
    isCandFechado: boolean | null;
    infoComplementar: string | null;
    cdSituacaoCassacao: number | null;
    cdSituacaoDiploma: number | null;
    legenda: string | null;
    cnpjcampanha: string | null;
    gastoCampanha: number;
    st_DIVULGA_BENS: boolean | null;
    st_DIVULGA_ARQUIVOS: boolean | null;
    st_SUBSTITUIDO: boolean | null;
    candidatoApto: boolean;
    descricaoNaturalidade: string;
    st_MOTIVO_FICHA_LIMPA: boolean | null;
    st_MOTIVO_ABUSO_PODER: boolean | null;
    st_MOTIVO_COMPRA_VOTO: boolean | null;
    st_MOTIVO_CONDUTA_VEDADA: boolean | null;
    st_MOTIVO_GASTO_ILICITO: boolean | null;
    ds_MOTIVO_OUTROS: string | null;
    st_MOTIVO_AUSENCIA_REQUISITO: boolean | null;
    st_MOTIVO_IND_PARTIDO: boolean | null;
    st_DIVULGA: boolean | null;
    st_REELEICAO: boolean;
};

export type RootObject = {
    unidadeEleitoral: UnidadeEleitoral;
    cargo: Cargo;
    candidatos: Candidato[];
};
